/**
 * Hydration Entry Point (Auto-generated by build-web.js)
 */

import { initHeader } from './components/header.hydrate.js';
import { initCarousels } from './components/carousel.hydrate.js';
import { initLightbox, initImageLightbox } from './components/lightbox.hydrate.js';
import { initPlaylists } from './components/audio.hydrate.js';
import { initPDFViewers } from './components/pdf.hydrate.js';
import { initGithubCards } from './components/github.hydrate.js';
import { initImmersiveNav } from './templates/immersive.hydrate.js';

function hydrate() {
    initHeader();
    initCarousels();
    initLightbox();
    initImageLightbox();
    initPlaylists();
    initPDFViewers();
    initGithubCards();
    initImmersiveNav();
    console.log('✨ Page hydrated');
}

if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', hydrate);
} else {
    hydrate();
}
